### PR TITLE
super awesome readme

### PR DESCRIPTION
**Pull request by Willster419**
This looks really good and I want it.

I don't have any complaints, but if possible i'd like to see if Arkhorse can see this through

### CODE REVIEW

**Comment by Willster419** [comment]
@elektrosmoker you should be able to work with @Nullmaruzero on a german version

**Review by Arkhorse — CHANGES_REQUESTED** [review]
Selection window has multiple options. Would be good to show them all, and how to change them. Also, the diagnostic button should be displayed. Maybe make this after a visual overhaul. It doesnt look good right now.

**Comment by Nullmaruzero** [comment]
I will get to that.

But since we are at it, perhaps a couple of beautifiers before the photo session?

Other than any redesign improvements you guys come up with, I have some flaws for the current design.
firefox_2020-12-14_17-35-12

1. The right edge for the components isn't aligned with the background border.
2. Perhaps some alignment to the right here. I know there is extra space due to translations having different lengths but maybe there can be done something about it. Perhaps drop Application Version and Database Version for the sake of a hint explaining those numbers upon hover. After all the flags on the bottom also explain that they are support links only after hover, despite looking a bit as if they were language selectors on a first glance (UI language).
3. Unify the button sizes? Smaller, larger.
4. Can the overlay over the background fixed in Dark Mode (and probably Custom modes), the same comes for the rightmost buttons on the bottom. I assume it comes due to technical limitations, but perhaps Willster is a bit smarter than he was back in the day and knows a way to hack it 👨‍💻

**Comment by Arkhorse** [comment]
Resized all the main window images to `16x16`. This looks better. `32x32` is too large for some of the images for some reason...
image

**Comment by Willster419** [comment]
huh i seem to have forgotten about this. Can we add it yet? I really like the overall appearance of the readme!

**Review by TylerTollefson — COMMENTED** [review]
This looks amazing! I love how clean it looks and all of the detail that is put into it. Integrating our various links is awesome too. Let's get this out there already.

**Review by elektrosmoker — APPROVED** [review]
i thought this was approved already?
engage! 
;)

**Pull request merged**
