### PR TITLE
100% translation coverage :D

### PR DESCRIPTION
**Pull request by Nullmaruzero**
Poor @SigmaTel71 being ignored on the channel 😞

### CODE REVIEW

**Comment by Willster419** [comment]
is this ready now? i can snag it if so. No rush :)

**Comment by Nullmaruzero** [comment]
I would say so, I just tagged folk because I was setting up VS on my new drive and wanted to check whether PL is falling behind. But since some of them answered I decided to act as a middle-man xD
LordFelix asked for the English strings he is missing but didn't return with the translations yet, so you may want to wait. Or they will PR later, probably, hopefully :P

**Comment by Willster419** [comment]
> Or they will PR later, probably, hopefully :P

🔜 ™️ ?

**Comment by SigmaTel71** [comment]
> Poor @SigmaTel71 being ignored on the channel

_meh_
That's not a problem.

**Comment by Nullmaruzero** [comment]
Now, i update some of the translations from Discord on my laptop, in VS Code instead of VS. My code formatting may be different there so you may want to look for some spacing issues before merge.

**Comment by SigmaTel71** [comment]
Will these translations be included in the next application update?

**Comment by Nullmaruzero** [comment]
> 
> 
> Will these translations be included in the next application update?

I freaking hope so xD Tbh @Willster419 wasn't very active recently so I assume he just did not have time to close all the PRs yet, or he's waiting for the ... you know ... a lost translation that someone lost due to an SSD failure...

**Comment by Willster419** [comment]
I didn't have time to work on the application because database. But with elektro back and the database smaller, we should be better off

**Comment by Willster419** [comment]
cloning out now to check for syntax and/or merge issues

**Review by Willster419 — APPROVED** [review]
Looks good from the web viewer. Able to compile and no merge conflicts

**Pull request merged**
